// Code generated by MockGen. DO NOT EDIT.
// Source: internal/providers/cloudru/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=internal/providers/cloudru/interfaces.go -destination=internal/providers/cloudru/mocks.go -package=cloudru
//

// Package cloudru is a generated GoMock package.
package cloudru

import (
	context "context"
	reflect "reflect"

	v1 "github.com/cloudru-tech/iam-sdk/api/auth/v1"
	v2 "github.com/cloudru-tech/secret-manager-sdk/api/v2"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MocksecretService is a mock of secretService interface.
type MocksecretService struct {
	ctrl     *gomock.Controller
	recorder *MocksecretServiceMockRecorder
	isgomock struct{}
}

// MocksecretServiceMockRecorder is the mock recorder for MocksecretService.
type MocksecretServiceMockRecorder struct {
	mock *MocksecretService
}

// NewMocksecretService creates a new mock instance.
func NewMocksecretService(ctrl *gomock.Controller) *MocksecretService {
	mock := &MocksecretService{ctrl: ctrl}
	mock.recorder = &MocksecretServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksecretService) EXPECT() *MocksecretServiceMockRecorder {
	return m.recorder
}

// Access mocks base method.
func (m *MocksecretService) Access(arg0 context.Context, arg1 *v2.AccessSecretRequest, arg2 ...grpc.CallOption) (*v2.AccessSecretResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Access", varargs...)
	ret0, _ := ret[0].(*v2.AccessSecretResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Access indicates an expected call of Access.
func (mr *MocksecretServiceMockRecorder) Access(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Access", reflect.TypeOf((*MocksecretService)(nil).Access), varargs...)
}

// Search mocks base method.
func (m *MocksecretService) Search(arg0 context.Context, arg1 *v2.SearchSecretRequest, arg2 ...grpc.CallOption) (*v2.SearchSecretResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Search", varargs...)
	ret0, _ := ret[0].(*v2.SearchSecretResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MocksecretServiceMockRecorder) Search(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MocksecretService)(nil).Search), varargs...)
}

// MockiamTokenClient is a mock of iamTokenClient interface.
type MockiamTokenClient struct {
	ctrl     *gomock.Controller
	recorder *MockiamTokenClientMockRecorder
	isgomock struct{}
}

// MockiamTokenClientMockRecorder is the mock recorder for MockiamTokenClient.
type MockiamTokenClientMockRecorder struct {
	mock *MockiamTokenClient
}

// NewMockiamTokenClient creates a new mock instance.
func NewMockiamTokenClient(ctrl *gomock.Controller) *MockiamTokenClient {
	mock := &MockiamTokenClient{ctrl: ctrl}
	mock.recorder = &MockiamTokenClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockiamTokenClient) EXPECT() *MockiamTokenClientMockRecorder {
	return m.recorder
}

// GetToken mocks base method.
func (m *MockiamTokenClient) GetToken(arg0 context.Context, arg1 *v1.GetTokenRequest, arg2 ...grpc.CallOption) (*v1.GetTokenResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetToken", varargs...)
	ret0, _ := ret[0].(*v1.GetTokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetToken indicates an expected call of GetToken.
func (mr *MockiamTokenClientMockRecorder) GetToken(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetToken", reflect.TypeOf((*MockiamTokenClient)(nil).GetToken), varargs...)
}
