// Code generated by MockGen. DO NOT EDIT.
// Source: provider.go
//
// Generated by this command:
//
//	mockgen -source=provider.go -destination=mocks.go -package=contracts
//

// Package contracts is a generated GoMock package.
package contracts

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockProvider is a mock of Provider interface.
type MockProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProviderMockRecorder
	isgomock struct{}
}

// MockProviderMockRecorder is the mock recorder for MockProvider.
type MockProviderMockRecorder struct {
	mock *MockProvider
}

// NewMockProvider creates a new mock instance.
func NewMockProvider(ctrl *gomock.Controller) *MockProvider {
	mock := &MockProvider{ctrl: ctrl}
	mock.recorder = &MockProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProvider) EXPECT() *MockProviderMockRecorder {
	return m.recorder
}

// Definition mocks base method.
func (m *MockProvider) Definition() ProviderDefinition {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Definition")
	ret0, _ := ret[0].(ProviderDefinition)
	return ret0
}

// Definition indicates an expected call of Definition.
func (mr *MockProviderMockRecorder) Definition() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Definition", reflect.TypeOf((*MockProvider)(nil).Definition))
}

// GetSecretPayload mocks base method.
func (m *MockProvider) GetSecretPayload(ctx context.Context, key string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecretPayload", ctx, key)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSecretPayload indicates an expected call of GetSecretPayload.
func (mr *MockProviderMockRecorder) GetSecretPayload(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecretPayload", reflect.TypeOf((*MockProvider)(nil).GetSecretPayload), ctx, key)
}

// ListSecrets mocks base method.
func (m *MockProvider) ListSecrets(ctx context.Context) (map[string]Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSecrets", ctx)
	ret0, _ := ret[0].(map[string]Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSecrets indicates an expected call of ListSecrets.
func (mr *MockProviderMockRecorder) ListSecrets(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSecrets", reflect.TypeOf((*MockProvider)(nil).ListSecrets), ctx)
}
