version: '3.8'

services:
  cloud-secrets:
    image: golang:1.26.2-alpine
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    working_dir: /app
    command: go run ./cmd/cloud-secrets/main.go
    environment:
      - CLOUDRU_PROJECT_ID=<cloudru-project-id>
      - CLOUDRU_IAM_CLIENT_ID=/var/run/secrets/iam_id
      - CLOUDRU_IAM_CLIENT_SECRET=/var/run/secrets/iam_secret
      - CLOUDRU_ROOT_FOLDER=/infra
      - CLOUDRU_ROOT_FOLDER_OMIT_PREFIX=true
      - CS_LOG_LEVEL=debug
      - CS_REFRESH_INTERVAL=12s
      - CS_CLEANUP_ORPHANED=false
      - CS_SECRET_NAME_FOLDER_DELIMITER=-
    secrets:
      - iam_id
      - iam_secret
    deploy:
      labels:
        - prometheus.port=8000
      placement:
        constraints:
          - node.role == manager

secrets:
  # Секреты для тестового приложения
  users-service-db-dsn:
    external: true
  # Креды для IAM
  iam_id:
    file: iam_id
  iam_secret:
    file: iam_secret
