// Code generated by MockGen. DO NOT EDIT.
// Source: api.go
//
// Generated by this command:
//
//	mockgen -source=api.go -destination=mocks_test.go -package=api
//

// Package api is a generated GoMock package.
package api

import (
	context "context"
	reflect "reflect"
	time "time"

	sync "github.com/swarm-deploy/cloud-secrets/internal/sync"
	gomock "go.uber.org/mock/gomock"
)

// MockSyncer is a mock of Syncer interface.
type MockSyncer struct {
	ctrl     *gomock.Controller
	recorder *MockSyncerMockRecorder
	isgomock struct{}
}

// MockSyncerMockRecorder is the mock recorder for MockSyncer.
type MockSyncerMockRecorder struct {
	mock *MockSyncer
}

// NewMockSyncer creates a new mock instance.
func NewMockSyncer(ctrl *gomock.Controller) *MockSyncer {
	mock := &MockSyncer{ctrl: ctrl}
	mock.recorder = &MockSyncerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSyncer) EXPECT() *MockSyncerMockRecorder {
	return m.recorder
}

// LastSyncAt mocks base method.
func (m *MockSyncer) LastSyncAt() (time.Time, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LastSyncAt")
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// LastSyncAt indicates an expected call of LastSyncAt.
func (mr *MockSyncerMockRecorder) LastSyncAt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LastSyncAt", reflect.TypeOf((*MockSyncer)(nil).LastSyncAt))
}

// NextSyncAt mocks base method.
func (m *MockSyncer) NextSyncAt() (time.Time, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NextSyncAt")
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// NextSyncAt indicates an expected call of NextSyncAt.
func (mr *MockSyncerMockRecorder) NextSyncAt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NextSyncAt", reflect.TypeOf((*MockSyncer)(nil).NextSyncAt))
}

// Sync mocks base method.
func (m *MockSyncer) Sync(ctx context.Context, trigger string) (sync.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sync", ctx, trigger)
	ret0, _ := ret[0].(sync.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Sync indicates an expected call of Sync.
func (mr *MockSyncerMockRecorder) Sync(ctx, trigger any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sync", reflect.TypeOf((*MockSyncer)(nil).Sync), ctx, trigger)
}
