// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -source=client.go -destination=mocks.go -package=engine
//

// Package engine is a generated GoMock package.
package engine

import (
	context "context"
	reflect "reflect"

	swarm "github.com/moby/moby/api/types/swarm"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// CreateSecret mocks base method.
func (m *MockClient) CreateSecret(ctx context.Context, spec CreatingSecret) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSecret", ctx, spec)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSecret indicates an expected call of CreateSecret.
func (mr *MockClientMockRecorder) CreateSecret(ctx, spec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSecret", reflect.TypeOf((*MockClient)(nil).CreateSecret), ctx, spec)
}

// CreateSecretVersion mocks base method.
func (m *MockClient) CreateSecretVersion(ctx context.Context, secret ExistingSecret, version CreatingSecretVersion) (CreatedSecretVersion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSecretVersion", ctx, secret, version)
	ret0, _ := ret[0].(CreatedSecretVersion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSecretVersion indicates an expected call of CreateSecretVersion.
func (mr *MockClientMockRecorder) CreateSecretVersion(ctx, secret, version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSecretVersion", reflect.TypeOf((*MockClient)(nil).CreateSecretVersion), ctx, secret, version)
}

// MapSecrets mocks base method.
func (m *MockClient) MapSecrets(ctx context.Context) (map[string]*ExistingSecret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MapSecrets", ctx)
	ret0, _ := ret[0].(map[string]*ExistingSecret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MapSecrets indicates an expected call of MapSecrets.
func (mr *MockClientMockRecorder) MapSecrets(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MapSecrets", reflect.TypeOf((*MockClient)(nil).MapSecrets), ctx)
}

// ListServices mocks base method.
func (m *MockClient) ListServices(ctx context.Context) ([]swarm.Service, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListServices", ctx)
	ret0, _ := ret[0].([]swarm.Service)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListServices indicates an expected call of ListServices.
func (mr *MockClientMockRecorder) ListServices(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListServices", reflect.TypeOf((*MockClient)(nil).ListServices), ctx)
}

// RemoveSecret mocks base method.
func (m *MockClient) RemoveSecret(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveSecret", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveSecret indicates an expected call of RemoveSecret.
func (mr *MockClientMockRecorder) RemoveSecret(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveSecret", reflect.TypeOf((*MockClient)(nil).RemoveSecret), ctx, id)
}

// UpdateService mocks base method.
func (m *MockClient) UpdateService(ctx context.Context, service swarm.Service) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateService", ctx, service)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateService indicates an expected call of UpdateService.
func (mr *MockClientMockRecorder) UpdateService(ctx, service any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateService", reflect.TypeOf((*MockClient)(nil).UpdateService), ctx, service)
}
