// Code generated by MockGen. DO NOT EDIT.
// Source: internal/providers/vault/api/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=internal/providers/vault/api/interfaces.go -destination=internal/providers/vault/api/mocks.go -package=api
//

// Package api is a generated GoMock package.
package api

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// AppRoleAuthEnabled mocks base method.
func (m *MockClient) AppRoleAuthEnabled(ctx context.Context) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppRoleAuthEnabled", ctx)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AppRoleAuthEnabled indicates an expected call of AppRoleAuthEnabled.
func (mr *MockClientMockRecorder) AppRoleAuthEnabled(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppRoleAuthEnabled", reflect.TypeOf((*MockClient)(nil).AppRoleAuthEnabled), ctx)
}

// CreateACLPolicy mocks base method.
func (m *MockClient) CreateACLPolicy(ctx context.Context, req CreateACLPolicyRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateACLPolicy", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateACLPolicy indicates an expected call of CreateACLPolicy.
func (mr *MockClientMockRecorder) CreateACLPolicy(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateACLPolicy", reflect.TypeOf((*MockClient)(nil).CreateACLPolicy), ctx, req)
}

// CreateAppRole mocks base method.
func (m *MockClient) CreateAppRole(ctx context.Context, req CreateAppRoleRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAppRole", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAppRole indicates an expected call of CreateAppRole.
func (mr *MockClientMockRecorder) CreateAppRole(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAppRole", reflect.TypeOf((*MockClient)(nil).CreateAppRole), ctx, req)
}

// CreateAppRoleSecretID mocks base method.
func (m *MockClient) CreateAppRoleSecretID(ctx context.Context, name string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAppRoleSecretID", ctx, name)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAppRoleSecretID indicates an expected call of CreateAppRoleSecretID.
func (mr *MockClientMockRecorder) CreateAppRoleSecretID(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAppRoleSecretID", reflect.TypeOf((*MockClient)(nil).CreateAppRoleSecretID), ctx, name)
}

// CreateSecret mocks base method.
func (m *MockClient) CreateSecret(ctx context.Context, path string, data map[string]any) (*Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSecret", ctx, path, data)
	ret0, _ := ret[0].(*Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSecret indicates an expected call of CreateSecret.
func (mr *MockClientMockRecorder) CreateSecret(ctx, path, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSecret", reflect.TypeOf((*MockClient)(nil).CreateSecret), ctx, path, data)
}

// CreateToken mocks base method.
func (m *MockClient) CreateToken(ctx context.Context, policies []string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateToken", ctx, policies)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateToken indicates an expected call of CreateToken.
func (mr *MockClientMockRecorder) CreateToken(ctx, policies any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateToken", reflect.TypeOf((*MockClient)(nil).CreateToken), ctx, policies)
}

// DeleteSecret mocks base method.
func (m *MockClient) DeleteSecret(ctx context.Context, path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSecret", ctx, path)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSecret indicates an expected call of DeleteSecret.
func (mr *MockClientMockRecorder) DeleteSecret(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSecret", reflect.TypeOf((*MockClient)(nil).DeleteSecret), ctx, path)
}

// EnableAppRoleAuth mocks base method.
func (m *MockClient) EnableAppRoleAuth(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnableAppRoleAuth", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnableAppRoleAuth indicates an expected call of EnableAppRoleAuth.
func (mr *MockClientMockRecorder) EnableAppRoleAuth(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnableAppRoleAuth", reflect.TypeOf((*MockClient)(nil).EnableAppRoleAuth), ctx)
}

// GetSecret mocks base method.
func (m *MockClient) GetSecret(ctx context.Context, path, key string) (*Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecret", ctx, path, key)
	ret0, _ := ret[0].(*Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSecret indicates an expected call of GetSecret.
func (mr *MockClientMockRecorder) GetSecret(ctx, path, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecret", reflect.TypeOf((*MockClient)(nil).GetSecret), ctx, path, key)
}

// ListKeys mocks base method.
func (m *MockClient) ListKeys(ctx context.Context, path string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListKeys", ctx, path)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListKeys indicates an expected call of ListKeys.
func (mr *MockClientMockRecorder) ListKeys(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListKeys", reflect.TypeOf((*MockClient)(nil).ListKeys), ctx, path)
}

// ReadAppRoleRoleID mocks base method.
func (m *MockClient) ReadAppRoleRoleID(ctx context.Context, name string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadAppRoleRoleID", ctx, name)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadAppRoleRoleID indicates an expected call of ReadAppRoleRoleID.
func (mr *MockClientMockRecorder) ReadAppRoleRoleID(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadAppRoleRoleID", reflect.TypeOf((*MockClient)(nil).ReadAppRoleRoleID), ctx, name)
}

// MockAuthenticator is a mock of Authenticator interface.
type MockAuthenticator struct {
	ctrl     *gomock.Controller
	recorder *MockAuthenticatorMockRecorder
	isgomock struct{}
}

// MockAuthenticatorMockRecorder is the mock recorder for MockAuthenticator.
type MockAuthenticatorMockRecorder struct {
	mock *MockAuthenticator
}

// NewMockAuthenticator creates a new mock instance.
func NewMockAuthenticator(ctrl *gomock.Controller) *MockAuthenticator {
	mock := &MockAuthenticator{ctrl: ctrl}
	mock.recorder = &MockAuthenticatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthenticator) EXPECT() *MockAuthenticatorMockRecorder {
	return m.recorder
}

// Authenticate mocks base method.
func (m *MockAuthenticator) Authenticate(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authenticate", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Authenticate indicates an expected call of Authenticate.
func (mr *MockAuthenticatorMockRecorder) Authenticate(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authenticate", reflect.TypeOf((*MockAuthenticator)(nil).Authenticate), ctx)
}
