name: e2e tests

on:
  push:
    branches: ['master']
  pull_request:

permissions:
  contents: read

jobs:
  swarm-test:
    runs-on: ubuntu-latest

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Initialize Swarm
        run: |
          docker swarm init --advertise-addr 127.0.0.1
          echo "Swarm mode is ready"

      - name: Install Go dependencies
        run: go mod download

      - name: Build Docker Images
        run: docker build . -t swarmdeployorg/cloud-secrets:local

      - name: Run Tests
        env:
          CS_E2E: 1
        run: go test ./e2e/...

      - name: Clean up Swarm
        if: always()
        run: |
          docker swarm leave --force
