name: Test Application in Docker Swarm

on:
  push:
    branches: ['master']
  pull_request:

jobs:
  swarm-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Initialize Docker Swarm
        run: |
          docker swarm init --advertise-addr 127.0.0.1
          echo "Swarm mode is ready"

      - name: Build Docker Images
        run: docker build . -t swarmdeployorg/cloud-secrets:local

      - name: Run Tests
        env:
          CS_E2E: 1
        run: go test ./e2e/...

      # 7. Очистка окружения после тестов (опционально)
      - name: Clean up Swarm Stack
        if: always()
        run: |
          docker swarm leave --force
